"""Resolve company names to real ATS board tokens, and verify them.

`config/companies.yaml` is GENERATED by this module rather than hand-written, so
the watchlist is reproducible and the finder can extend it the same way.

The important lesson encoded here: **a live API call returning jobs does NOT
prove the token is the right company.** Mining tokens by fuzzy name match against
the aggregator corpus produced these real false positives:

    IMC Trading        -> ING            (workday tenant "ing")
    Old Mission        -> Old Republic Title
    Texas Instruments  -> Texas A&M University System
    Applied Intuition  -> Applied Materials
    Meta               -> KoboldMetals
    Rippling           -> ING

Every one of those tokens is a real, live board that returns hundreds of jobs, so
"HTTP 200 and count > 0" accepts all of them. Verification therefore cross-checks
the board's SELF-REPORTED company name where the ATS provides one (Greenhouse and
SmartRecruiters do), and otherwise requires the token itself to look like the
company. That is what `verify_token` does.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from difflib import SequenceMatcher
from typing import Any

import requests

from .adapters import ashby, greenhouse, lever, smartrecruiters, workday
from .http import FetchError

log = logging.getLogger(__name__)

# Corporate suffixes that differ between a company's common name and its legal
# name on a job board ("Palantir" vs "Palantir Technologies").
_SUFFIXES = re.compile(
    r"\b(inc|llc|ltd|corp|corporation|technologies|technology|labs|group|holdings|"
    r"company|co|plc|gmbh|securities|capital|partners|systems|solutions|global|"
    r"international|industries|the)\b",
    re.IGNORECASE,
)


def normalize_company(name: str) -> str:
    """Reduce a company name to a comparable core token."""
    n = name.lower().replace("&", " and ")
    n = _SUFFIXES.sub(" ", n)
    return re.sub(r"[^a-z0-9]", "", n)


def name_matches(a: str, b: str, threshold: float = 0.86) -> bool:
    """Whether two company names plausibly denote the same company.

    Deliberately NOT substring containment: "imc" is a substring of nothing
    useful, but naive containment matched "Applied Intuition" to "Applied
    Materials" and "Meta" to "KoboldMetals". Requires either equality of the
    normalized forms or a high ratio, and never accepts a match where one name is
    a short prefix of a much longer one.
    """
    na, nb = normalize_company(a), normalize_company(b)
    if not na or not nb:
        return False
    if na == nb:
        return True
    # A board may report a shorter trading name than the one we watch for:
    # Greenhouse's "imc" board reports "IMC" while our watchlist says "IMC
    # Trading". A prefix relationship is safe where containment is not --
    # "koboldmetals" does not start with "meta", and "appliedmaterials" does not
    # start with "appliedintuition", so the earlier false positives stay rejected.
    if len(min(na, nb, key=len)) >= 3 and (na.startswith(nb) or nb.startswith(na)):
        return True
    # A short name embedded in a long one is the classic false positive.
    if abs(len(na) - len(nb)) > max(4, min(len(na), len(nb)) // 2):
        return False
    return SequenceMatcher(None, na, nb).ratio() >= threshold


@dataclass
class Candidate:
    company: str
    ats: str
    token: str
    site: str | None = None  # workday only
    host: str | None = None  # workday only
    evidence: int = 0        # listings agreeing on this token

    def key(self) -> tuple[str, ...]:
        return (self.ats, self.token, self.site or "", self.host or "")


URL_PATTERNS: dict[str, re.Pattern[str]] = {
    "greenhouse": re.compile(r"(?:job-boards|boards)\.greenhouse\.io/([^/?#]+)"),
    "lever": re.compile(r"jobs\.lever\.co/([^/?#]+)"),
    "ashby": re.compile(r"jobs\.ashbyhq\.com/([^/?#]+)"),
    "smartrecruiters": re.compile(r"jobs\.smartrecruiters\.com/([^/?#]+)"),
    "workday": re.compile(
        r"https?://([a-z0-9-]+)\.(wd\d+)\.myworkdayjobs\.com/"
        r"(?:[a-z]{2}-[A-Z]{2}/)?([^/?#]+)"
    ),
}


def mine_candidates(rows: list[dict[str, Any]]) -> dict[str, list[Candidate]]:
    """Extract (company -> candidate tokens) from aggregator apply URLs.

    Measured against ~33k real listings: about 67% carry a resolvable token, with
    Workday the largest single slice.
    """
    found: dict[str, dict[tuple[str, ...], Candidate]] = {}
    for row in rows:
        company = (row.get("company_name") or "").strip()
        if not company:
            continue
        for url in (row.get("url") or "", row.get("company_url") or ""):
            if not url:
                continue
            cand = _match_url(company, url)
            if cand is None:
                continue
            bucket = found.setdefault(company, {})
            existing = bucket.get(cand.key())
            if existing:
                existing.evidence += 1
            else:
                cand.evidence = 1
                bucket[cand.key()] = cand
            break
    return {c: sorted(v.values(), key=lambda x: -x.evidence) for c, v in found.items()}


def _match_url(company: str, url: str) -> Candidate | None:
    for ats, pattern in URL_PATTERNS.items():
        m = pattern.search(url)
        if not m:
            continue
        if ats == "workday":
            tenant, wd, site = m.groups()
            return Candidate(company, ats, tenant, site=site,
                             host=f"{tenant}.{wd}.myworkdayjobs.com")
        return Candidate(company, ats, m.group(1))
    return None


@dataclass
class Verification:
    ok: bool
    count: int = 0
    reported_name: str | None = None
    status: int | None = None
    error: str | None = None


def verify_token(cand: Candidate, *, session: requests.Session | None = None,
                 strict_name: bool = True) -> Verification:
    """Live-check a candidate token AND confirm it belongs to the right company."""
    try:
        payload, count, reported = _probe(cand, session)
    except FetchError as exc:
        return Verification(False, status=exc.status, error=str(exc))
    except requests.RequestException as exc:
        return Verification(False, error=str(exc))

    if count == 0:
        return Verification(False, 0, reported, error="board returned zero jobs")

    if strict_name:
        if reported:
            if not name_matches(cand.company, reported):
                return Verification(
                    False, count, reported,
                    error=f"board belongs to {reported!r}, not {cand.company!r}",
                )
        elif cand.evidence >= 2:
            # Provenance beats appearance. This token was extracted from the apply
            # URLs of >=2 listings that the aggregator itself attributes to this
            # company, which is stronger evidence than whether the token happens
            # to spell the company's name. Applied Materials' Workday tenant is
            # "amat" -- correct, and unrecognizable by string similarity alone.
            pass
        elif not name_matches(cand.company, cand.token):
            # No self-reported name (Lever, Ashby, Workday): the token itself must
            # look like the company, which is what catches IMC -> "ing".
            return Verification(
                False, count, reported,
                error=f"token {cand.token!r} does not resemble {cand.company!r}",
            )
    return Verification(True, count, reported)


def _probe(cand: Candidate, session: requests.Session | None) -> tuple[Any, int, str | None]:
    if cand.ats == "greenhouse":
        res = greenhouse.fetch(cand.token, cand.company, session=session)
        payload_name = res.listings[0].company if res.listings else None
        _raise_if_failed(res)
        return None, res.count, payload_name
    if cand.ats == "lever":
        res = lever.fetch(cand.token, cand.company, session=session)
        _raise_if_failed(res)
        return None, res.count, None
    if cand.ats == "ashby":
        res = ashby.fetch(cand.token, cand.company, session=session)
        _raise_if_failed(res)
        return None, res.count, None
    if cand.ats == "smartrecruiters":
        res = smartrecruiters.fetch(cand.token, cand.company, session=session, max_pages=1)
        _raise_if_failed(res)
        return None, res.count, res.listings[0].company if res.listings else None
    if cand.ats == "workday":
        res = workday.fetch(cand.token, cand.site or "", cand.host or "",
                            cand.company, session=session, max_pages=1)
        _raise_if_failed(res)
        return None, res.count, None
    raise FetchError(f"unknown ats {cand.ats}")


def _raise_if_failed(res: Any) -> None:
    if not res.ok:
        raise FetchError(res.error or "board fetch failed", res.status)
